language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_TEST=testing
services:
  - postgresql
before_script:
  - psql -c 'create database bussiness_card_test;' -U postgres
notifications:
  email: false