language: node_js
node_js:
  - "stable"
install: 
  npm install
  travis_wait mvn install
cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_TEST=testing
services:
  - postgresql
script: npm test
notifications:
  email: false
