language: node_js
node_js:
  - "stable"
install: 
  npm install
  travis_wait mvn install
cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_TEST=testing
services:
  - postgresql
before_script:
  - psql -c 'create database bussiness_card_test;' -U postgres
  - psql -c "CREATE USER username WITH PASSWORD 'password';" -U postgres
after_success:
  - npm run coverage
install: travis_wait mvn install
script: npm test
notifications:
  email: false
